[package]
name = "asdasdas"
version = "0.0.0"
upgrade_policy = "compatible"

[addresses]
hello_blockchain = "afd848a070e55f593f739bdacab6c1c9b526abd39ae8b6f0dd60a53f9db2cebc"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'
